spring.application.name=backend
server.servlet.context-path=/api/v1

management.endpoints.web.exposure.include=health,info

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/candidate_upskill}
spring.datasource.username=${DATABASE_USERNAME:candidate_upskill}
spring.datasource.password=${DATABASE_PASSWORD:candidate_upskill}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
